datasources:
  default:
    url: 'jdbc:postgresql://google/<DATABASE_NAME>?cloudSqlInstance=<INSTANCE_CONNECTION_NAME>&socketFactory=com.google.cloud.sql.postgres.SocketFactory'
    username: '<USER NAME>'
    password: '<PASSWORD>'
    dialect: POSTGRES
